# action.yml
name: 'TSL Build and Test'
description: 'Build and tests .'
inputs:
  compiler:
    description: "Name of compiler."
    required: true
    type: string
  tsl:
    description: "Path to the TSL source code."
    required: true
    type: string
outputs:
  name:
    description: 'Name of the generated files.'
  out:
    description: 'Path to the generated files.'
  msg:
    description: 'Verbose message from the action.'
  success:
    description: 'Whether the action was successful (1, 0 otherwise).'
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - uses: 'docker://jpietrzyktud/tsl_build_and_test_arm:latest'
      with:
        args: "${{ inputs.compiler }} ${{ inputs.tsl }}"