name: 'Create Environment for TSL generation'
description: 'Create the environment for generating the Template SIMD Library for a specific architecture.'
inputs:
  requirement-file: 
    description: 'Path to the requirement file.'
    required: true
    type: string
  docker-tag:
    description: 'Docker tag for the resulting image.'
    required: true
    type: string
  context:
    description: 'Path to the context directory of the Dockerfile.'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Copy python requirements to actions
      run: cp ${{ inputs.requirement-file }} ${{ inputs.context }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ inputs.docker-tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
