# action.yml
name: 'TSL Generate'
description: 'Generate the Template SIMD Library for a specific architecture.'
inputs:
  targets:
    description: "Comma separated list of targets to generate, e.g., 'sse,sse2,sse4_1'."
    required: true
    type: string
  xxx:
    description: 'Docker image to use for the action.'
    required: false
    default: 'Dockerfile'
    type: string
outputs:
  out:
    description: 'Path to the generated files.'
  logs:
    description: 'Path to the logs.'
  msg:
    description: 'Verbose message from the action.'
  success:
    description: 'Whether the action was successful (1, 0 otherwise).'
runs:
  using: 'docker'
  image: ${{ inputs.xxx }}
  args:
    - ${{ inputs.targets }}