# action.yml
name: 'TSL Build and Test'
description: 'Build and tests .'
inputs:
  compiler:
    description: "Name of compiler."
    required: true
    type: string
outputs:
  name:
    description: 'Name of the generated files.'
  out:
    description: 'Path to the generated files.'
  msg:
    description: 'Verbose message from the action.'
  success:
    description: 'Whether the action was successful (1, 0 otherwise).'
runs:
  using: 'docker'
  image: 'docker://jpietrzyktud/tsl_generator:latest'
  args:
    - ${{ inputs.compiler }}