# action.yml
name: 'TSL Package DEB'
description: 'Builds deb.'
inputs:
  tag:
    description: "Release Tag."
    required: true
    type: string
  tsl:
    description: "Path to the hollistic TSL tarball."
    required: true
    type: string
  prefix:
    description: "Prefix of directories in the tarball."
    required: true
    type: string
outputs:
  name:
    description: 'Name of the generated deb file.'
  out:
    description: 'Path to the generated files.'
  msg:
    description: 'Verbose message from the action.'
  success:
    description: 'Whether the action was successful (1, 0 otherwise).'
runs:
  using: 'docker'
  image: 'docker://jpietrzyktud/tsl_package_deb:latest'
  args:
    - ${{ inputs.tag }}
    - ${{ inputs.tsl }}
    - ${{ inputs.prefix }}