
name: Auto-Tag

on:
  workflow-call:
    outputs:
      tag: 
        description: 'The tag to be used for the release'
        value: ${{ jobs.auto-tag.outputs.tag }}


jobs:
  auto-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - name: Get the tag
        id: get_tag
        run: |
          LATEST_TAG=$(git tag --sort=version:refname | head -n 1)
          if [ -z "$LATEST_TAG" ]; then
            echo "v0.0.0"
          fi
          LATEST_TAG=${LATEST_TAG:1}
          MAJOR=${LATEST_TAG%%.*}
          TEMP=${LATEST_TAG#*.}
          MINOR=${TEMP%%.*}
          PATCH=${TEMP#*.}
          if [ $PATCH -eq 9 ]; then
            MINOR=$((MINOR+1))
            PATCH=0
          else
            PATCH=$((PATCH+1))
          fi
          if [ $MINOR -eq 10 ]; then
            MAJOR=$((MAJOR+1))
            MINOR=0
          fi
          VERSION="v$MAJOR.$MINOR.$PATCH"
          echo "New tag: $VERSION"
          git push origin --delete latest
          git tag -a $VERSION -m "Auto-tagged by GitHub Actions"
          git tag -a latest -f -m "Auto-tagged by GitHub Actions"
          git push origin --tags
          echo "tag=${VERSION}" >> $GITHUB_OUTPUT