name: create-build-and-test-images
run-name: Create a docker image for TSL building and testing
on: [push]

jobs:
  setup-generation:
    uses: ./.github/workflows/setup-environment.yml    
    with:
      requirement-file: "requirements.txt"
      docker-tag: "${{ vars.GENERATION_TAG }}"
      context: ".github/actions/tsl-generate"
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_PASSWORD }}
  setup-x86:
    uses: ./.github/workflows/setup-environment.yml    
    with:
      requirement-file: "requirements.txt"
      docker-tag: "${{ vars.BUILD_TEST_x86_TAG }}"
      context: ".github/actions/tsl-test-x86"
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_PASSWORD }}
  setup-arm:
    uses: ./.github/workflows/setup-environment.yml    
    with:
      requirement-file: "requirements.txt"
      docker-tag: "${{ vars.BUILD_TEST_ARM_TAG }}"
      context: ".github/actions/tsl-test-arm"
      platforms: linux/amd64,linux/arm64
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_PASSWORD }}