name: create-validation-image
run-name: Create a docker image for TSL validation

# on: [push]
on: 
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, edited]
    
jobs:
  setup:
    uses: ./.github/workflows/setup-environment.yml    
    with:
      requirement-file: "requirements.txt"
      docker-tag: "${{ vars.VALIDATION_TAG}}"
      context: ".github/actions/tsl-validate"
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_PASSWORD }}