name: create-generation-image
run-name: Create a docker image for TSL generation
on:
  workflow_run:
    workflows: [create-build-and-test-image]
    types:
      - completed

jobs:
  setup:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/setup-environment.yml    
    with:
      requirement-file: "requirements.txt"
      docker-tag: "${{ vars.GENERATION_TAG }}"
      context: ".github/actions/tsl-generate"
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_PASSWORD }}