on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy python requirements to actions
        run: cp requirements.txt .github/actions/tsl-generate/
      - name: TSL Generate
        id: generate
        uses: ./.github/actions/tsl-generate
        with:
          targets: 'sse,sse2,ssse3,sse4_1,sse4_2,avx,avx2'
          generate-to: 'TSL'
      - name: TSL Generate Output
        if: always()
        run: echo "TSL Generation ${{ steps.generate.outputs.msg }}"
      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: generation-logs
          path: ${{ github.workspace }}/${{ steps.generate.outputs.logs }}

