on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy python requirements to actions
        run: cp requirements.txt .github/actions/tsl-generate/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./.github/actions/tsl-generate
          push: true
          tags: jpietrzyktud/tsl_generator:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      # - uses: docker/build-push-action@v5
      #   id: build-docker
      #   with:
      #     context: ./.github/actions/tsl-generate
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
      - name: TSL Generate
        id: generate
        uses: ./.github/actions/tsl-generate
        with:
          targets: 'sse,sse2,ssse3,sse4_1,sse4_2,avx,avx2'
      - name: TSL Generate Output
        if: always()
        run: echo "TSL Generation ${{ steps.generate.outputs.msg }}"
      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: generation-logs
          path: ${{ github.workspace }}/${{ steps.generate.outputs.logs }}
          overwrite: true

