name: generate-tsl-matrix
run-name: Generate the Template SIMD Library

on:
  workflow_run:
    workflows: [create-generation-image]
    types:
      - completed

jobs:
  generate-for-intel:
    runs-on: ubuntu-latest
    name: Job to generate TSL for Intel x86
    strategy:
      matrix:
        target_flags:
          - "sse"
          - "sse,sse2"
          - "sse,sse2,ssse3"
          - "sse,sse2,ssse3,sse4_1"
          - "sse,sse2,ssse3,sse4_1,sse4_2"
          - "sse,sse2,ssse3,sse4_1,sse4_2,avx"
          - "sse,sse2,ssse3,sse4_1,sse4_2,avx,avx2"
          - "sse,sse2,ssse3,sse4_1,sse4_2,avx,avx2,avx512f"
          - "sse,sse2,ssse3,sse4_1,sse4_2,avx,avx2,avx512f,avx512cd,avx512er,avx512pf" #avx3.1
          - "sse,sse2,ssse3,sse4_1,sse4_2,avx,avx2,avx512f,avx512cd,avx512bw,avx512dq,avx512vl" #avx3.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: TSL Generate
        id: generate
        uses: ./.github/actions/tsl-generate
        with:
          targets: ${{ matrix.target_flags }}
      - name: TSL Generate Output
        if: always()
        run: echo "TSL Generation ${{ steps.generate.outputs.msg }}"
      - name: Upload Generated TSL
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TSL_intel_${{ steps.generate.outputs.name }}
          path: ${{ github.workspace }}/${{ steps.generate.outputs.out }}
          overwrite: true
  package-for-intel:
    runs-on: ubuntu-latest
    name: Job to package TSL for Intel x86
    needs: generate-for-intel
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Generated TSL
        uses: actions/download-artifact@v4
        with:
          pattern: TSL_intel_*
          path: ${{ github.workspace }}/tsl_intel
      - name: Upload Packaged TSL
        uses: actions/upload-artifact@v4
        with:
          name: TSL_intel
          path: ${{ github.workspace }}/tsl_intel
          overwrite: true
      - name: Garbage Collect
        uses: geekyeggo/delete-artifact@v4
        with:
          name: TSL_intel_*
