name: Publish latest version of TSL

on:
  workflow_run:
    workflows: [create-package-images]
    types:
      - completed
      
jobs:
  auto-tag:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Auto-Tag current Head
    permissions: write-all
    outputs:
      tag: ${{ steps.push-tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Auto-Tag
        id: push-tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git tag -l --sort=-v:refname "v*" | head -n 1)
          if [ -z "${LATEST_TAG}" ]; then
            echo "No tag: $LATEST_TAG"
            LATEST_TAG=v0.0.0
          else
            echo "Latest tag: $LATEST_TAG"
          fi
          LATEST_TAG=${LATEST_TAG:1}
          echo "latest=${LATEST_TAG}"
          MAJOR=${LATEST_TAG%%.*}
          echo "major=${MAJOR}"
          TEMP=${LATEST_TAG#*.}
          echo "temp=${TEMP}"
          MINOR=${TEMP%%.*}
          echo "minor=${MINOR}"
          PATCH=${TEMP#*.}
          echo "patch=${PATCH}"
          PATCH=$((PATCH+1))
          VERSION="v$MAJOR.$MINOR.$PATCH"
          echo "tag=${VERSION}"
          echo "tag=${VERSION}" >> $GITHUB_OUTPUT
          git config --global user.email "johannes.pietrzyk@tu-dresden.de"
          git config --global user.name "GitHub Action (Maintainer: Johannes Pietrzyk)"
          git tag -a $VERSION -m "${VERSION} (Auto-tagged by GitHub Actions)"
          git push origin --tags
  release-on-push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: auto-tag
    permissions: write-all
    uses: ./.github/workflows/release-tsl.yml    
    with:
      tag-name: ${{ needs.auto-tag.outputs.tag }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  
  get-tag:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    name: Get Tag
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Tag
        id: get-tag
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
  release-on-tag:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: get-tag
    permissions: write-all
    uses: ./.github/workflows/release-tsl.yml    
    with:
      tag-name: ${{ needs.get-tag.outputs.tag }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}