on:
  workflow_call:
    inputs:
      requirement-file: 
        description: 'Path to the requirement file.'
        required: true
        type: string
      docker-tag:
        description: 'Docker tag for the resulting image.'
        required: true
        type: string
      context:
        description: 'Path to the context directory of the Dockerfile.'
        required: true
        type: string
    secrets:
      DOCKERHUB_USER:
        description: 'Dockerhub username.'
        required: true
      DOCKERHUB_TOKEN:
        description: 'Dockerhub token.'
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Job to setup environment (build and push docker image)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy python requirements to actions
        run: cp ${{ inputs.requirement-file }} ${{ inputs.context }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          push: true
          tags: ${{ inputs.docker-tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  