name: validate-tsl-matrix
run-name: Validate the TSL Generator

on:
  workflow_run:
    workflows: [create-validation-image]
    types:
      - completed

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Job to validate the TSL Generator
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: TSL Validate
        id: validate
        uses: ./.github/actions/tsl-validate
        with:
          python-version: ${{ matrix.python_version }}
          image: ${{ vars.VALIDATION_TAG }}
      - name: TSL Generate Output
        if: always()
        run: echo "TSL Validation output ${{ steps.validate.outputs.msg }}. Name is ${{ steps.validate.outputs.name }}"
      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validate_${{ steps.validate.outputs.name }}
          path: ${{ github.workspace }}/${{ steps.validate.outputs.out }}
          overwrite: true
      - if: ${{ steps.validate.outputs.success }} != 1
        uses: actions/github-script@v7
        with:
          script: |
            echo "TSL Generation ${{ steps.validate.outputs.success }}"
            core.setFailed("${{ steps.validate.outputs.msg }}")

