name: Generating with py3.8-3.12
run-name: Validate the TSL Generator

on:
  workflow_run:
    workflows: [create-validation-image]
    types:
      - completed

jobs:
  validate:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Job to validate the TSL Generator
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout PR and merge
        uses: check-spelling/checkout-merge@v0.0.4
      - name: Cancel on Merge fail
        if: env.MERGE_FAILED == '1'
        run:
          echo "Merge failed, cancelling the job"
          exit 1
      - name: TSL Validate
        id: validate
        uses: ./.github/actions/tsl-validate
        with:
          python-version: ${{ matrix.python_version }}
          image: ${{ vars.VALIDATION_TAG }}
      - name: TSL Generate Output
        if: always()
        run: echo "TSL Validation output ${{ steps.validate.outputs.msg }}. Name is ${{ steps.validate.outputs.name }}"
      - if: ${{ steps.validate.outputs.success == 'false' }}
        run: "echo SUCCESS == false"
      - if: ${{ steps.validate.outputs.success == 'true' }}
        run: "echo SUCCESS == true"
      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validate_${{ steps.validate.outputs.name }}
          path: ${{ github.workspace }}/${{ steps.validate.outputs.out }}
          overwrite: true
          retention-days: 1
      - if: ${{ steps.validate.outputs.success == 'false' }}
        run: |
          echo "Validation failed"
          echo "${{ steps.validate.outputs.msg }}"
          exit 1

